name: CD_NLP
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - flair>=0.11
    - pycld2
    - torchinfo
    - textattack[transformers]
    - tensorflow_hub
    - tensorflow